### ISSUE TITLE
`NoMethodError` when  `receive` and `have_receive` are aliased with `alias_matcher`. Conflicts with ActiveSupport's `Object#with`

### ISSUE THREAD

**Issue by pucinsk** [rspec/rspec#146]
### Subject of the issue
Rails 7.1 added [Object#with](https://api.rubyonrails.org/classes/Object.html#method-i-with) which conflicts with `receive` and `have_received` that define a #with method (chain :with) when used via an alias_matcher.

Related issue: https://github.com/rspec/rspec-expectations/issues/1437 (solved)

### Your environment
* Ruby version: 3.2.2
* rspec-expectations version: 3.13.0
* Rails version: 7.1.3.2

### Steps to reproduce
```ruby
require "rails_helper"

RSpec::Matchers.alias_matcher :have_received_alias, :have_received
RSpec::Matchers.alias_matcher :receive_alias, :receive

RSpec.describe "Foo" do
  it do
    expect(1).to have_received_alias(:foo_bar).with(foo: :bar)
  end

  it do
    expect(1).to receive_alias(:foo_bar).with(foo: :bar)
  end
end

```

### Expected behavior
Neither assert should raise an `NoMethodError`

### Actual behavior
Arguments passed for `with` method are treated as Object methods.

```bash
Failures:

  1) Foo 
     Failure/Error: expect(1).to receive_alias(:foo_bar).with(foo: :bar)
     
     NoMethodError:
       undefined method `foo' for #<RSpec::Mocks::Matchers::Receive:0x00000001107d1868>
     # ./spec/dummy_spec.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:233:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:147:in `block (2 levels) in <top (required)>'

  2) Foo 
     Failure/Error: expect(1).to have_received_alias(:foo_bar).with(foo: :bar)
     
     NoMethodError:
       undefined method `foo' for #<RSpec::Mocks::Matchers::HaveReceived:0x0000000128478b68 @method_name=:foo_bar, @block=nil, @constraints=[], @subject=nil>
     # ./spec/dummy_spec.rb:10:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:233:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:147:in `block (2 levels) in <top (required)>'

Finished in 2.84 seconds (files took 10.64 seconds to load)
2 examples, 2 failures
```

**Comment by DylanEtris** [comment]
I was able to reproduce the issue with the setup from the description, and it does look like this problem is load order dependent. As it is, RSpec's BaseDelegator patch runs before the Rails' Object patch:
```sh
➜  tmp git:(master) ✗ bundle exec rspec

[1, 10] in /home/etrisdylan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/rspec-expectations-3.13.0/lib/rspec/matchers/aliased_matcher.rb
    1: require 'byebug'; byebug
=>  2: module RSpec
    3:   module Matchers
    4:     # Decorator that wraps a matcher and overrides `description`
    5:     # using the provided block in order to support an alias
    6:     # of a matcher. This is intended for use when composing
    7:     # matchers, so that you can use an expression like
    8:     # `include( a_value_within(0.1).of(3) )` rather than
    9:     # `include( be_within(0.1).of(3) )`, and have the corresponding
   10:     # description read naturally.
(byebug) c

[1, 10] in /home/etrisdylan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activesupport-7.1.3.2/lib/active_support/core_ext/object/with.rb
    1: # frozen_string_literal: true
    2: require 'byebug'; byebug
=>  3: class Object
    4:   # Set and restore public attributes around a block.
    5:   #
    6:   #   client.timeout # => 5
    7:   #   client.with(timeout: 1) do
    8:   #     client.timeout # => 1
    9:   #   end
   10:   #   client.timeout # => 5
(byebug)
```

If I move `require 'rails_helper.rb'` to the first line of `spec_helper.rb`, the load order is reversed and the problem goes away.

**Comment by TomNaessens** [comment]
We've encountered a similar issue here when switching to Rails 7.1 (on the latest version of rspec-expectations, 3.13.3). In our case, we have a negated matchers which fails with the same exception:

```ruby
RSpec::Matchers.define_negated_matcher :not_have_enqueued_job, :have_enqueued_job
```

As a negated matcher uses an `alias_matcher` under the hood, I believe the cause is the same.

But only after a combination with `and`, for example:

```ruby
expect do
  enqueue_a_job!
end.to have_enqueued_job(SomeJob).with(some_args).and not_have_enqueued_job(SomeOtherJob).with(some_other_args)
```

On that example, calls to `with` with `some_first_args` works as expected, but with `some_second_args` is handled by `with` method added in the ActiveSupport extension in Rails 7.1.

To work around this, without having to change our setup, we've added a monkeypatch:

```ruby
  class RSpec::Matchers::AliasedMatcher
    def with(...)
      if base_matcher.respond_to?(:with)
        return_val = base_matcher.with(...)
        return return_val unless RSpec::Matchers.is_a_matcher?(return_val)
        self.class.new(return_val, @description_block)
      else
        super
      end
    end
  end
```

**Comment by roharon** [comment]
Any updates? 👀
