### ISSUE TITLE
Warning[:deprecated] = true by default in RSpec

### ISSUE THREAD

**Issue by eregon** [rspec/rspec#37]
### Subject of the issue

See https://bugs.ruby-lang.org/issues/17591.

The plan of ruby-core hiding deprecation warnings in Ruby 2.7.2 is that test frameworks, like rspec, should enable them by default (with `Warning[:deprecated] = true if Warning.respond_to?(:[]=)`, which only enables deprecation warnings).
This is important so that developers see warnings in development, and that they see the warnings before updating to the next Ruby version.

Of course, RSpec users can still choose to disable deprecation warnings explicitly if they really want with `Warning[:deprecated] = false` (but then they should not be surprised when it breaks hard when updating to a newer Ruby, that's the cost of ignoring deprecation warnings).

Somewhat related to https://github.com/rspec/rspec-core/issues/2809.

### Your environment
* Ruby version: 2.7.2
* rspec-core version: 3.10.1

### Steps to reproduce
```ruby
# some_spec.rb 
def foo(**kwargs)
  kwargs
end

RSpec.describe 'Test' do
  it "should warn about keyword arguments" do
    expect(foo({a: 1})).to eq({a: 1})
  end
end
```

`rspec some_spec.rb`

### Expected behavior
```
$ rspec some_spec.rb
/home/eregon/code/rspec-ws/some_spec.rb:7: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/home/eregon/code/rspec-ws/some_spec.rb:1: warning: The called method `foo' is defined here
.

Finished in 0.00154 seconds (files took 0.05064 seconds to load)
1 example, 0 failures
```
### Actual behavior
No warnings in 2.7:
```
$ rspec some_spec.rb
.

Finished in 0.00157 seconds (files took 0.05947 seconds to load)
1 example, 0 failures
```

Breaks hard in 3.0:
```
$ rspec some_spec.rb
F

Failures:

  1) Test should warn about keyword arguments
     Failure/Error:
       def foo(**kwargs)
         kwargs
       end
     
     ArgumentError:
       wrong number of arguments (given 1, expected 0)
     # ./some_spec.rb:1:in `foo'
     # ./some_spec.rb:7:in `block (2 levels) in <top (required)>'

Finished in 0.00121 seconds (files took 0.05637 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./some_spec.rb:6 # Test should warn about keyword arguments
```

**Comment by byroot** [comment]
> I'll happily review a PR with a config option that sets this, and prints a warning if its not set for Rubies that support it;

I submitted a PR here: https://github.com/rspec/rspec/pull/161.
