### ISSUE TITLE
doc_string which is the first argument of example, must be string object

### ISSUE THREAD

**Issue by eisukeyeongjo** [rspec/rspec#40]
### doc_string which is the first argument of example, must be string object

RSpec example recognize the first argument as the description.
But when even symbol or hash object which set intended as metadata is given in the first argument, it is recognized as the description and metadata does not work.
I want to add some change to keep doc_string a string object.

### Your environment
* Ruby version: 3.3.0
* rspec-core version: 3.1.3

### Steps to reproduce
**prepare rspec test below**

```
$ vi test.rb
$ cat test.rb
```

```ruby
context do
  it :pending do
    expect(true).to eq false
  end

  it pending: 'some reason' do
    expect(true).to eq false   
  end
end
```

### Actual behavior
metadata is recognized as description and pending does not work, failing two examples

```
$ bundle exec rspec  test.rb --format documentation

  pending (FAILED - 1)
  {:pending=>"some reason"} (FAILED - 2)

Failures:

  1) pending
     Failure/Error: expect(true).to eq false
     
       expected: false
            got: true
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -false
       +true
       
     # ./test.rb:14:in `block (2 levels) in <top (required)>'

  2) {:pending=>"some reason"}
     Failure/Error: expect(true).to eq false
     
       expected: false
            got: true
     
       (compared using ==)
     
       Diff:
       @@ -1 +1 @@
       -false
       +true
       
     # ./test.rb:18:in `block (2 levels) in <top (required)>'

Finished in 0.01336 seconds (files took 0.08613 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./test.rb:13 # pending
rspec ./test.rb:17 # {:pending=>"some reason"}
```

### Expected behavior
To prevent metadata as first argument which does not work properly, it raises ArgumentError like below when execute each example above whose first argument is not nil or string object.

```
ArgumentError:
  `:pending` is not acceptable for doc_string.
  it must be a string.
```

### Note
First, I created PR rspec/rspec-core#3074 not to set doc_string when first argument is metadata.
But I think that keeping the first argument of example doc_string is much more appropriate.
(In the first place, as commented [here](https://github.com/rspec/rspec-core/blob/main/lib/rspec/core/example_group.rb#L114)  it's the specification.)

### Related Pull Request
I proposed this new specification in the PR below,
After the discussion, we decided to add this in upcoming 4.x and add warning in 3.99

https://github.com/rspec/rspec-core/pull/3071

### What to do
- [ ] Add warning for upcoming breaking change in 4.0 rspec/rspec-core#3073 
- [x] Raise ArgumentError when doc_string is neither string nor nil rspec/rspec-core#3081

**Comment by pirj** [comment]
This is what I could find with grep in [real-world-rspec](https://github.com/pirj/real-world-rspec).
If you exclude our own code, those cbase global namespace const literals (due to the incorrect search pattern), `:aggregate_failures`, there's not much left at all.

real-world-rspec born out of https://github.com/jeromedalbert/real-world-ruby-apps and https://github.com/eliotsykes/real-world-rails, filtered by using RSpec.

Am I missing something? Maybe `feature`/`scenario`?

```
$ rg '^\s*(describe|it|context|example|specify)\s+[:\[\d]'
rspec/rspec-core/spec/rspec/core/formatters/documentation_formatter_spec.rb
72:  context 1
75:    context 1.1
78:  context 2
126:    example 1
127:    example 2 (PENDING: No reason given)
128:    example 3 (FAILED - 1)

rspec/rspec-core/features/hooks/filtering.feature
236:      example 1
238:      example 2
242:      example 4

cartodb/services/dataservices-metrics/spec/unit/service_usage_metrics_spec.rb
39:  describe :assert_valid_amount do
61:  describe :incr do

puppet/spec/unit/plan_spec.rb
18:  describe :naming do

puppet/spec/unit/task_spec.rb
202:  describe :metadata do
251:  describe :validate do

puppet/spec/unit/etc_spec.rb
369:  describe :getgrent do
373:  describe :getgrnam do
382:  describe :getgrgid do
391:  describe :getpwent do
395:  describe :getpwnam do
404:  describe :getpwuid do
413:  describe :group do

mastodon/spec/lib/activitypub/adapter_spec.rb
18:      context :security

mastodon/app/serializers/activitypub/public_key_serializer.rb
4:  context :security

mastodon/app/serializers/activitypub/actor_serializer.rb
7:  context :security

solidus/backend/spec/features/admin/users_spec.rb
389:    context :number do
398:    context :total do

discourse/plugins/discourse-gamification/spec/plugin_spec.rb
3:describe ::DiscourseGamification do
24:describe ::DiscourseGamification do

discourse/plugins/discourse-ai/spec/requests/topic_spec.rb
3:describe ::TopicsController do

chef/spec/unit/util/windows/logon_session_spec.rb
22:describe ::Chef::Util::Windows::LogonSession do

canvas-lms/gems/canvas_partman/spec/canvas_partman/concerns/partitioned_spec.rb
21:  context :by_date do
183:  context :by_id do

canvas-lms/gems/canvas_partman/spec/canvas_partman/partition_manager_spec.rb
29:  context :by_date do
129:  context :by_id do

gitlabhq/doc/ci/jobs/ci_job_token.md
151:it [compacts the allowlist](#allowlist-compaction) to stay under the 200 entry limit.

gitlabhq/spec/services/git/branch_push_service_spec.rb
648:      specify :aggregate_failures do

gitlabhq/spec/requests/api/projects_spec.rb
5545:      it :aggregate_failures do
5554:      it :aggregate_failures do

gitlabhq/spec/services/merge_requests/base_service_spec.rb
33:      specify :aggregate_failures do

gitlabhq/spec/controllers/projects_controller_spec.rb
1230:      specify :aggregate_failures do
1240:      specify :aggregate_failures do
1302:        specify :aggregate_failures do
1312:        specify :aggregate_failures do

gitlabhq/spec/workers/concerns/packages/error_handling_spec.rb
49:      it :aggregate_failures do

gitlabhq/spec/requests/api/ci/pipelines_spec.rb
425:        it :aggregate_failures do
439:        it :aggregate_failures do
459:        it :aggregate_failures do
627:          it :skip_before_request, :aggregate_failures do
640:          it :skip_before_request, :aggregate_failures do

gitlabhq/spec/workers/releases/manage_evidence_worker_spec.rb
9:    specify :sidekiq_inline do

gitlabhq/spec/policies/group_policy_spec.rb
314:    it :aggregate_failures do
331:      it :aggregate_failures do

gitlabhq/spec/tasks/gitlab/backup_rake_spec.rb
466:        specify :aggregate_failures do

gitlabhq/spec/tooling/danger/datateam_spec.rb
136:      it :aggregate_failures do

gitlabhq/spec/features/security/project/snippet/private_access_spec.rb
17:    specify :aggregate_failures do
35:    specify :aggregate_failures do
53:    specify :aggregate_failures do
71:    specify :aggregate_failures do

gitlabhq/spec/lib/gitlab/search_context/controller_concern_spec.rb
37:    it :aggregate_failures do

gitlabhq/spec/support/shared_examples/models/wiki_shared_examples.rb
844:        specify :aggregate_failures do
```

Maybe `feature`/`scenario`?

```
$ rg '^\s*(feature|scenario)\s+[:\[\d]'
puppet/lib/puppet/type/user.rb
25:    feature :allows_duplicates,
28:    feature :manages_homedir,
... (a bunch more sumilar unrelated from Puppet
```
